# Generated by Django 6.1 on 2026-10-01 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=7)),
                ('subtransaction_type', models.CharField(choices=[('food', 'Food'), ('housing', 'housing'), ('personal', 'Personal'), ('transportation', 'Transportation'), ('financial', 'Financial'), ('earned', 'Earned'), ('portfolio', 'Portfolio'), ('passive', 'Passive')], max_length=14, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually'), ('n/a', 'N/A')], max_length=8, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('message', models.TextField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
