# Generated by Django 6.1 on 2026-09-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subtransaction_type',
            field=models.CharField(choices=[('food', 'Food'), ('housing', 'housing'), ('personal', 'Personal'), ('transportation', 'Transportation'), ('financial', 'Financial'), ('earned', 'Earned'), ('portfolio', 'Portfolio'), ('passive', 'Passive')], max_length=14, null=True),
        ),
    ]
