# Generated by Django 6.1 on 2026-10-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_transaction_recurring_transaction_recurring_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recurring_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually'), ('n/a', 'N/A')], max_length=8, null=True),
        ),
    ]
